name: lint
on: pull_request
jobs:
  lint-code:
    runs-on: ubuntu-latest
    name: Lint code
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint scripts
        run: npm run lint:scripts

      - name: Lint styles
        run: npm run lint:styles
